# .github/settings.yml
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI / Golang CI Pipeline"                         # ci.yml (workflow / job)
          - "Security Gate / SBOM & Vulnerability Scan"       # security.yml (workflow / job)
          - "Integration Tests / Integration Tests"           # integration.yml (workflow / job)
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
