name: Publish Image
on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write    # 修正: 署名をここで実行

jobs:
  publish:
    name: Build, Publish & Sign Image
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push image
        run: |
          docker build -t ghcr.io/7lycka/sre-workflow:${{ github.sha }} .
          docker push ghcr.io/7lycka/sre-workflow:${{ github.sha }}
      
      # ダイジェスト取得
      - name: Get image digest
        id: digest
        run: |
          digest=$(docker buildx imagetools inspect ghcr.io/7lycka/sre-workflow:${{ github.sha }} | awk '/Digest: sha256/ {print $2; exit}')
          echo "digest=$digest" >> $GITHUB_OUTPUT
          echo "Image digest: $digest"
      
      # 修正: 署名をmainでのみ実行（公式アクション使用）
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
      
      - name: Sign container image
        run: cosign sign --yes ghcr.io/7lycka/sre-workflow@${{ steps.digest.outputs.digest }}
      
      # 推奨: SBOM再生成＋アテステーション添付
      - name: Generate SBOM for attestation
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            anchore/syft ghcr.io/7lycka/sre-workflow:${{ github.sha }} -o spdx-json > sbom.spdx.json
      
      - name: Attest SBOM
        run: |
          cosign attest --yes \
            --predicate sbom.spdx.json --type spdx \
            ghcr.io/7lycka/sre-workflow@${{ steps.digest.outputs.digest }}